name: Generate

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true

jobs:
  vim-basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate
        run: ./generate-basic.sh
      - name: Zip
        run: |
          cd ./generated
          zip -r ./vim-basic.zip ./vim-basic
      - uses: ncipollo/release-action@v1
        with:
          name: "${{ github.event.inputs.version }}"
          tag: "${{ github.event.inputs.version }}"
          artifacts: "generated/vim-basic.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
